/*
 * gui_config.h
 *
 *  Created on: 2016年10月7日
 *      Author: YJ-User17
 */

#ifndef STM32F4_BOARD_MASTER_STM32F4_BOARD_MASTER_GUI_GUI_CONFIG_GUI_CONFIG_H_
#define STM32F4_BOARD_MASTER_STM32F4_BOARD_MASTER_GUI_GUI_CONFIG_GUI_CONFIG_H_


#define GUI_OPTIMIZE_SUPPORT          (1)

#define GUI_WIDTH_PIXEL_DEFAULT       (320)
#define GUI_HEIGHT_PIXEL_DEFAULT      (240)

#endif /* STM32F4_BOARD_MASTER_STM32F4_BOARD_MASTER_GUI_GUI_CONFIG_GUI_CONFIG_H_ */
